#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential', '~> 1.4.4'
cookbook 'yum'
cookbook 'vim'

cookbook 'rvm', 
  :git => 'git://github.com/fnichol/chef-rvm.git'

cookbook 'git', 
  :git => 'https://github.com/fnichol/chef-git.git'

cookbook 'postgresql',
  :git => 'https://github.com/hw-cookbooks/postgresql.git'

cookbook 'nodejs', git: 'https://github.com/mdxp/nodejs-cookbook.git'
